[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config.basedpyright.analysis]
autoSearchPaths = true
useLibraryCodeForTypes = true
typeCheckingMode = "basic" # Change to "strict" if needed
diagnosticMode = "openFilesOnly"

[language-server.basedpyright.config.basedpyright.analysis.diagnosticSeverityOverrides]
reportArgumentType = "warning"
reportAssignmentType = "warning"
reportAttributeAccessIssue = false
reportCallIssue = "warning"
reportGeneralTypeIssues = "warning"
reportOptionalMemberAccess = false
reportOptionalSubscript = false
reportPrivateImportUsage = false
reportUndefinedVariable = false
reportUnusedImport = false
reportUnusedParameter = "warning"
reportUnusedVariable = "warning"

[[language]]
name = "python"
auto-format = false
# formatter = { command = "ruff", args = ["format", "--line-length", "120", "-"] }
formatter = { command = "format-git-hunks.py", args=["%{buffer_name}"]}
language-servers = ["basedpyright"]

